apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshpod-deployment
  labels:
    app: sshpod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sshpod
  template:
    metadata:
      labels:
        app: sshpod
    spec:
      containers:
        - name: sshpod
          image: quay.io/jwmatthews/sshpod:v0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 2222
              name: ssh
              protocol: TCP
