apiVersion: v1
kind: Pod
metadata:
  name: sshpod
  namespace: sshpod
  labels:
    app: sshpod
spec:
  containers:
  - name: myapp-container
    image: quay.io/jwmatthews/sshpod:v0.3
    ports:
    - containerPort: 2222
      name: ssh
      protocol: TCP
