apiVersion: v1
kind: Service
metadata:
  labels:
    app: sshpod
  name: sshpod
  namespace: sshpod
spec:
  ports:
  - name: ssh
    port: 2222
    protocol: TCP
    targetPort: 2222
  selector:
    app: sshpod
  type: LoadBalancer
